# Generated by Django 2.2.5 on 2019-11-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='iamgeurl',
            field=models.CharField(default='To be Added', max_length=1000),
        ),
        migrations.AddField(
            model_name='item',
            name='imagename',
            field=models.CharField(default='To be Added', max_length=1000),
        ),
    ]
