# Generated by Django 2.2.5 on 2019-11-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20191109_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=7),
        ),
    ]
