# Generated by Django 2.2.5 on 2019-11-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20191110_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bidders',
            field=models.CharField(default='', max_length=9999),
        ),
    ]
