# Generated by Django 2.2.5 on 2019-11-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20191111_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='email',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
